// Code generated by Wire protocol buffer compiler, do not edit.
// Source: test.Shipment in parsing/parsing.proto
package misk.web.metadata.protos

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import okio.ByteString

public class Shipment(
  @SemanticDataTypeOption([
    Type.SHIPMENT_ID
  ])
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    schemaIndex = 0,
  )
  public val shipment_id: Long? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val shipment_token: String? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.protos.test.parsing.Warehouse#ADAPTER",
    schemaIndex = 2,
  )
  public val source: Warehouse? = null,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.protos.test.parsing.Warehouse#ADAPTER",
    schemaIndex = 3,
  )
  public val destination: Warehouse? = null,
  @SemanticDataTypeOption([
    Type.STATUS
  ])
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.protos.test.parsing.Shipment${'$'}State#ADAPTER",
    schemaIndex = 4,
  )
  public val status: State? = null,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    schemaIndex = 5,
  )
  public val load_ratio: Double? = null,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    schemaIndex = 6,
  )
  public val deleted: Boolean? = null,
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    schemaIndex = 7,
  )
  public val source_signature: ByteString? = null,
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    schemaIndex = 8,
  )
  public val destination_signature: ByteString? = null,
  notes: List<String> = emptyList(),
  @SemanticDataTypeOption([
    Type.ACCOUNT_TOKEN
  ])
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    oneofName = "PaymentType",
    schemaIndex = 10,
  )
  public val account_token: String? = null,
  @SemanticDataTypeOption([
    Type.CARD_TOKEN
  ])
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    oneofName = "PaymentType",
    schemaIndex = 11,
  )
  public val card_token: String? = null,
  @SemanticDataTypeOption([
    Type.TRANSFER_ID
  ])
  @field:WireField(
    tag = 15,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    oneofName = "PaymentType",
    schemaIndex = 12,
  )
  public val transfer_id: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Shipment, Nothing>(ADAPTER, unknownFields) {
  @SemanticDataTypeOption([
    Type.NOTE_TYPE_1,
    Type.NOTE_TYPE_2
  ])
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 9,
  )
  public val notes: List<String> = immutableCopyOf("notes", notes)

  init {
    require(countNonNull(account_token, card_token, transfer_id) <= 1) {
      "At most one of account_token, card_token, transfer_id may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
  AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Shipment) return false
    if (unknownFields != other.unknownFields) return false
    if (shipment_id != other.shipment_id) return false
    if (shipment_token != other.shipment_token) return false
    if (source != other.source) return false
    if (destination != other.destination) return false
    if (status != other.status) return false
    if (load_ratio != other.load_ratio) return false
    if (deleted != other.deleted) return false
    if (source_signature != other.source_signature) return false
    if (destination_signature != other.destination_signature) return false
    if (notes != other.notes) return false
    if (account_token != other.account_token) return false
    if (card_token != other.card_token) return false
    if (transfer_id != other.transfer_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (shipment_id?.hashCode() ?: 0)
      result = result * 37 + (shipment_token?.hashCode() ?: 0)
      result = result * 37 + (source?.hashCode() ?: 0)
      result = result * 37 + (destination?.hashCode() ?: 0)
      result = result * 37 + (status?.hashCode() ?: 0)
      result = result * 37 + (load_ratio?.hashCode() ?: 0)
      result = result * 37 + (deleted?.hashCode() ?: 0)
      result = result * 37 + (source_signature?.hashCode() ?: 0)
      result = result * 37 + (destination_signature?.hashCode() ?: 0)
      result = result * 37 + notes.hashCode()
      result = result * 37 + (account_token?.hashCode() ?: 0)
      result = result * 37 + (card_token?.hashCode() ?: 0)
      result = result * 37 + (transfer_id?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (shipment_id != null) result += """shipment_id=$shipment_id"""
    if (shipment_token != null) result += """shipment_token=${sanitize(shipment_token)}"""
    if (source != null) result += """source=$source"""
    if (destination != null) result += """destination=$destination"""
    if (status != null) result += """status=$status"""
    if (load_ratio != null) result += """load_ratio=$load_ratio"""
    if (deleted != null) result += """deleted=$deleted"""
    if (source_signature != null) result += """source_signature=$source_signature"""
    if (destination_signature != null) result += """destination_signature=$destination_signature"""
    if (notes.isNotEmpty()) result += """notes=${sanitize(notes)}"""
    if (account_token != null) result += """account_token=${sanitize(account_token)}"""
    if (card_token != null) result += """card_token=${sanitize(card_token)}"""
    if (transfer_id != null) result += """transfer_id=${sanitize(transfer_id)}"""
    return result.joinToString(prefix = "Shipment{", separator = ", ", postfix = "}")
  }

  public fun copy(
    shipment_id: Long? = this.shipment_id,
    shipment_token: String? = this.shipment_token,
    source: Warehouse? = this.source,
    destination: Warehouse? = this.destination,
    status: State? = this.status,
    load_ratio: Double? = this.load_ratio,
    deleted: Boolean? = this.deleted,
    source_signature: ByteString? = this.source_signature,
    destination_signature: ByteString? = this.destination_signature,
    notes: List<String> = this.notes,
    account_token: String? = this.account_token,
    card_token: String? = this.card_token,
    transfer_id: String? = this.transfer_id,
    unknownFields: ByteString = this.unknownFields,
  ): Shipment = Shipment(shipment_id, shipment_token, source, destination, status, load_ratio,
    deleted, source_signature, destination_signature, notes, account_token, card_token,
    transfer_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Shipment> = object : ProtoAdapter<Shipment>(
      FieldEncoding.LENGTH_DELIMITED,
      Shipment::class,
      "type.googleapis.com/test.Shipment",
      PROTO_2,
      null,
      "parsing/parsing.proto"
    ) {
      override fun encodedSize(`value`: Shipment): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.INT64.encodedSizeWithTag(1, value.shipment_id)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.shipment_token)
        size += Warehouse.ADAPTER.encodedSizeWithTag(4, value.source)
        size += Warehouse.ADAPTER.encodedSizeWithTag(5, value.destination)
        size += State.ADAPTER.encodedSizeWithTag(6, value.status)
        size += ProtoAdapter.DOUBLE.encodedSizeWithTag(7, value.load_ratio)
        size += ProtoAdapter.BOOL.encodedSizeWithTag(8, value.deleted)
        size += ProtoAdapter.BYTES.encodedSizeWithTag(9, value.source_signature)
        size += ProtoAdapter.BYTES.encodedSizeWithTag(10, value.destination_signature)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(12, value.notes)
        size += ProtoAdapter.STRING.encodedSizeWithTag(13, value.account_token)
        size += ProtoAdapter.STRING.encodedSizeWithTag(14, value.card_token)
        size += ProtoAdapter.STRING.encodedSizeWithTag(15, value.transfer_id)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Shipment) {
        ProtoAdapter.INT64.encodeWithTag(writer, 1, value.shipment_id)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.shipment_token)
        Warehouse.ADAPTER.encodeWithTag(writer, 4, value.source)
        Warehouse.ADAPTER.encodeWithTag(writer, 5, value.destination)
        State.ADAPTER.encodeWithTag(writer, 6, value.status)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 7, value.load_ratio)
        ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.deleted)
        ProtoAdapter.BYTES.encodeWithTag(writer, 9, value.source_signature)
        ProtoAdapter.BYTES.encodeWithTag(writer, 10, value.destination_signature)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 12, value.notes)
        ProtoAdapter.STRING.encodeWithTag(writer, 13, value.account_token)
        ProtoAdapter.STRING.encodeWithTag(writer, 14, value.card_token)
        ProtoAdapter.STRING.encodeWithTag(writer, 15, value.transfer_id)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Shipment) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 15, value.transfer_id)
        ProtoAdapter.STRING.encodeWithTag(writer, 14, value.card_token)
        ProtoAdapter.STRING.encodeWithTag(writer, 13, value.account_token)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 12, value.notes)
        ProtoAdapter.BYTES.encodeWithTag(writer, 10, value.destination_signature)
        ProtoAdapter.BYTES.encodeWithTag(writer, 9, value.source_signature)
        ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.deleted)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 7, value.load_ratio)
        State.ADAPTER.encodeWithTag(writer, 6, value.status)
        Warehouse.ADAPTER.encodeWithTag(writer, 5, value.destination)
        Warehouse.ADAPTER.encodeWithTag(writer, 4, value.source)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.shipment_token)
        ProtoAdapter.INT64.encodeWithTag(writer, 1, value.shipment_id)
      }

      override fun decode(reader: ProtoReader): Shipment {
        var shipment_id: Long? = null
        var shipment_token: String? = null
        var source: Warehouse? = null
        var destination: Warehouse? = null
        var status: State? = null
        var load_ratio: Double? = null
        var deleted: Boolean? = null
        var source_signature: ByteString? = null
        var destination_signature: ByteString? = null
        val notes = mutableListOf<String>()
        var account_token: String? = null
        var card_token: String? = null
        var transfer_id: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> shipment_id = ProtoAdapter.INT64.decode(reader)
            2 -> shipment_token = ProtoAdapter.STRING.decode(reader)
            4 -> source = Warehouse.ADAPTER.decode(reader)
            5 -> destination = Warehouse.ADAPTER.decode(reader)
            6 -> try {
              status = State.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            7 -> load_ratio = ProtoAdapter.DOUBLE.decode(reader)
            8 -> deleted = ProtoAdapter.BOOL.decode(reader)
            9 -> source_signature = ProtoAdapter.BYTES.decode(reader)
            10 -> destination_signature = ProtoAdapter.BYTES.decode(reader)
            12 -> notes.add(ProtoAdapter.STRING.decode(reader))
            13 -> account_token = ProtoAdapter.STRING.decode(reader)
            14 -> card_token = ProtoAdapter.STRING.decode(reader)
            15 -> transfer_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Shipment(
          shipment_id = shipment_id,
          shipment_token = shipment_token,
          source = source,
          destination = destination,
          status = status,
          load_ratio = load_ratio,
          deleted = deleted,
          source_signature = source_signature,
          destination_signature = destination_signature,
          notes = notes,
          account_token = account_token,
          card_token = card_token,
          transfer_id = transfer_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Shipment): Shipment = value.copy(
        source = value.source?.let(Warehouse.ADAPTER::redact),
        destination = value.destination?.let(Warehouse.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class State(
    override val `value`: Int,
  ) : WireEnum {
    VALIDATING(0),
    PICKING_UP(1),
    DELIVERING(2),
    CONSUMING(4),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<State> = object : EnumAdapter<State>(
        State::class,
        PROTO_2,
        State.VALIDATING
      ) {
        override fun fromValue(`value`: Int): State? = State.fromValue(value)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): State? = when (value) {
        0 -> VALIDATING
        1 -> PICKING_UP
        2 -> DELIVERING
        4 -> CONSUMING
        else -> null
      }
    }
  }
}
