// Code generated by Wire protocol buffer compiler, do not edit.
// Source: test.Type in customoption.proto
package misk.web.metadata.protos

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int

public enum class Type(
  override val `value`: Int,
) : WireEnum {
  SHIPMENT_ID(1),
  SHIPMENT_TOKEN(2),
  ACCOUNT_TOKEN(3),
  CARD_TOKEN(4),
  TRANSFER_ID(5),
  NOTE_TYPE_1(6),
  NOTE_TYPE_2(7),
  STATUS(8),
  WAREHOUSE_TOKEN(9),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Type> = object : EnumAdapter<Type>(
      Type::class,
      PROTO_2,
      null
    ) {
      override fun fromValue(`value`: Int): Type? = Type.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): Type? = when (value) {
      1 -> SHIPMENT_ID
      2 -> SHIPMENT_TOKEN
      3 -> ACCOUNT_TOKEN
      4 -> CARD_TOKEN
      5 -> TRANSFER_ID
      6 -> NOTE_TYPE_1
      7 -> NOTE_TYPE_2
      8 -> STATUS
      9 -> WAREHOUSE_TOKEN
      else -> null
    }
  }
}
