// Code generated by Wire protocol buffer compiler, do not edit.
// Source: test.type in customoption.proto
package misk.web.metadata.protos

import kotlin.Array
import kotlin.`annotation`.AnnotationRetention
import kotlin.`annotation`.AnnotationTarget
import kotlin.`annotation`.Retention
import kotlin.`annotation`.Target

@Retention(AnnotationRetention.RUNTIME)
@Target(
  AnnotationTarget.PROPERTY,
  AnnotationTarget.FIELD,
)
public annotation class TypeOption(
  public val `value`: Array<Type>,
)
