// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: service.proto
package com.squareup.digester.protos.service;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class GetDigestsResponse extends Message<GetDigestsResponse, GetDigestsResponse.Builder> {
  public static final ProtoAdapter<GetDigestsResponse> ADAPTER = new ProtoAdapter_GetDigestsResponse();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.digester.protos.service.MetricFamily#ADAPTER"
  )
  public final MetricFamily metric_family;

  public GetDigestsResponse(MetricFamily metric_family) {
    this(metric_family, ByteString.EMPTY);
  }

  public GetDigestsResponse(MetricFamily metric_family, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.metric_family = metric_family;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.metric_family = metric_family;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetDigestsResponse)) return false;
    GetDigestsResponse o = (GetDigestsResponse) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(metric_family, o.metric_family);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (metric_family != null ? metric_family.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (metric_family != null) builder.append(", metric_family=").append(metric_family);
    return builder.replace(0, 2, "GetDigestsResponse{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetDigestsResponse, Builder> {
    public MetricFamily metric_family;

    public Builder() {
    }

    public Builder metric_family(MetricFamily metric_family) {
      this.metric_family = metric_family;
      return this;
    }

    @Override
    public GetDigestsResponse build() {
      return new GetDigestsResponse(metric_family, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetDigestsResponse extends ProtoAdapter<GetDigestsResponse> {
    public ProtoAdapter_GetDigestsResponse() {
      super(FieldEncoding.LENGTH_DELIMITED, GetDigestsResponse.class);
    }

    @Override
    public int encodedSize(GetDigestsResponse value) {
      return MetricFamily.ADAPTER.encodedSizeWithTag(1, value.metric_family)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetDigestsResponse value) throws IOException {
      MetricFamily.ADAPTER.encodeWithTag(writer, 1, value.metric_family);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetDigestsResponse decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.metric_family(MetricFamily.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetDigestsResponse redact(GetDigestsResponse value) {
      Builder builder = value.newBuilder();
      if (builder.metric_family != null) builder.metric_family = MetricFamily.ADAPTER.redact(builder.metric_family);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
