plugins {
  kotlin("jvm")
  `java-library`
}

dependencies {
  api(libs.awsJavaSdkCore)
  api(libs.awsS3)
  api(libs.awsSqs)
  api(libs.guice)
  api(libs.javaxInject)
  api(libs.wispAwsEnvironment)
  api(libs.wispConfig)
  api(libs.wispLease)
  api(project(":misk"))
  api(project(":misk-config"))
  api(project(":misk-feature"))
  api(project(":misk-inject"))
  api(project(":misk-jobqueue"))
  implementation(libs.kotlinLogging)
  implementation(libs.moshi)
  implementation(libs.openTracingApi)
  implementation(libs.openTracingDatadog)
  implementation(libs.openTracingDatadogApi)
  implementation(libs.prometheusClient)
  implementation(libs.slf4jApi)
  implementation(libs.wispDeployment)
  implementation(libs.wispLogging)
  implementation(project(":misk-core"))
  implementation(project(":misk-hibernate"))
  implementation(project(":misk-metrics"))
  implementation(project(":misk-service"))
  implementation(project(":misk-transactional-jobqueue"))

  testImplementation(libs.assertj)
  testImplementation(libs.awaitility)
  testImplementation(libs.dockerApi)
  testImplementation(libs.junitApi)
  testImplementation(libs.junitParams)
  testImplementation(libs.kotlinTest)
  testImplementation(libs.mockitoCore)
  testImplementation(libs.wispContainersTesting)
  testImplementation(libs.wispFeatureTesting)
  testImplementation(libs.wispTimeTesting)
  testImplementation(project(":misk-clustering"))
  testImplementation(project(":misk-feature-testing"))
  testImplementation(project(":misk-testing"))
}
