version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.datadoghq:dd-trace-ot"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
