package misk.hibernate

/**
 * Put this on a column field for a class generated by Wire to get Hibernate to persist with protobuf serialization.
 *
 * There is no defensive copy when reading from the database as protobufs are assumed to be immutable.
 */
@Target(AnnotationTarget.FIELD) annotation class ProtoColumn
