plugins {
  kotlin("jvm")
  `java-library`
}

dependencies {
  api(Dependencies.gax)
  api(Dependencies.gcpCloudCore)
  api(Dependencies.gcpCloudStorage)
  api(Dependencies.gcpDatastore) {
    exclude(group = "com.google.protobuf")
    exclude(group = "com.google.api.grpc")
    exclude(group = "io.grpc")
  }
  api(Dependencies.gcpKms)
  api(Dependencies.gcpLogging)
  api(Dependencies.gcpSpanner)
  api(Dependencies.googleApiServicesStorage)
  api(Dependencies.googleAuthLibraryCredentials)
  api(Dependencies.guice)
  api(Dependencies.javaxInject)
  api(Dependencies.logbackClassic)
  api(Dependencies.moshi)
  api(Dependencies.okio)
  api(Dependencies.openTracingApi)
  api(Dependencies.wispConfig)
  api(Dependencies.wispDeployment)
  api(project(":misk-config"))
  api(project(":misk-inject"))
  implementation(Dependencies.gcpLogback)
  implementation(Dependencies.googleApiClient)
  implementation(Dependencies.googleAuthLibraryOauth2)
  implementation(Dependencies.googleCloudCoreHttp)
  implementation(Dependencies.googleHttpClient)
  implementation(Dependencies.googleHttpClientJackson)
  implementation(Dependencies.kotlinLogging)
  implementation(Dependencies.logbackCore)
  implementation(Dependencies.openTracingDatadog)
  implementation(Dependencies.slf4jApi)
  implementation(Dependencies.wireRuntime)
  implementation(Dependencies.wispLogging)
  implementation(Dependencies.wispMoshi)
  implementation(project(":misk"))
  implementation(project(":misk-service"))

  testImplementation(Dependencies.assertj)
  testImplementation(Dependencies.junitApi)
  testImplementation(Dependencies.kotlinTest)
  testImplementation(Dependencies.openTracingDatadog)
  testImplementation(Dependencies.wispContainersTesting)
  testImplementation(project(":misk-gcp"))
  testImplementation(project(":misk-gcp-testing"))
  testImplementation(project(":misk-testing"))
}
