dependencies {
  implementation(Dependencies.datasourceProxy)
  implementation(Dependencies.guice)
  implementation(Dependencies.hikariCp)
  implementation(Dependencies.loggingApi)
  implementation(Dependencies.moshiCore)
  implementation(Dependencies.moshiKotlin)
  implementation(Dependencies.moshiAdapters)
  implementation(Dependencies.okHttp)
  api(project(":misk"))
  api(project(":misk-core"))
  api(project(":misk-inject"))
  api(project(":misk-jdbc"))
  api(project(":misk-service"))
  api(project(":misk-testing"))
  api(project(":wisp-logging"))

  testImplementation(project(":wisp-config"))
  testImplementation(Dependencies.junitApi)
  testImplementation(Dependencies.openTracingDatadog)
  testImplementation(Dependencies.assertj)
  testImplementation(Dependencies.kotlinTest)
}

apply(from = "$rootDir/gradle-mvn-publish.gradle")
