plugins {
  kotlin("jvm")
  `java-library`
}

dependencies {
  api(libs.gax)
  api(libs.gcpCloudCore)
  api(libs.gcpCloudStorage)
  api(libs.gcpDatastore) {
    exclude(group = "com.google.protobuf")
    exclude(group = "com.google.api.grpc")
    exclude(group = "io.grpc")
  }
  api(libs.gcpKms)
  api(libs.gcpLogging)
  api(libs.gcpSpanner)
  api(libs.googleApiServicesStorage)
  api(libs.googleAuthLibraryCredentials)
  api(libs.guice)
  api(libs.javaxInject)
  api(libs.logbackClassic)
  api(libs.moshi)
  api(libs.okio)
  api(libs.openTracingApi)
  api(libs.wispConfig)
  api(libs.wispDeployment)
  api(project(":misk-config"))
  api(project(":misk-inject"))
  implementation(libs.gcpLogback)
  implementation(libs.googleApiClient)
  implementation(libs.googleAuthLibraryOauth2)
  implementation(libs.googleCloudCoreHttp)
  implementation(libs.googleHttpClient)
  implementation(libs.googleHttpClientJackson)
  implementation(libs.kotlinLogging)
  implementation(libs.logbackCore)
  implementation(libs.openTracingDatadog)
  implementation(libs.slf4jApi)
  implementation(libs.wireRuntime)
  implementation(libs.wispLogging)
  implementation(libs.wispMoshi)
  implementation(project(":misk"))
  implementation(project(":misk-service"))

  testImplementation(libs.assertj)
  testImplementation(libs.junitApi)
  testImplementation(libs.kotlinTest)
  testImplementation(libs.openTracingDatadog)
  testImplementation(libs.wispContainersTesting)
  testImplementation(project(":misk-gcp-testing"))
  testImplementation(project(":misk-testing"))
}
