plugins {
  kotlin("jvm")
  `java-library`
}

dependencies {
  api(Dependencies.datasourceProxy)
  api(Dependencies.dockerApi)
  api(Dependencies.dockerCore)
  api(Dependencies.javaxInject)
  api(Dependencies.moshi)
  api(Dependencies.openTracingApi)
  api(Dependencies.prometheusClient)
  api(Dependencies.wispConfig)
  api(Dependencies.wispDeployment)
  api(project(":misk-config"))
  api(project(":misk-core"))
  api(project(":misk-inject"))
  implementation(Dependencies.dockerTransport)
  implementation(Dependencies.dockerTransportHttpClient)
  implementation(Dependencies.guice)
  implementation(Dependencies.hikariCp)
  implementation(Dependencies.kotlinLogging)
  implementation(Dependencies.okio)
  implementation(Dependencies.wispLogging)
  implementation(Dependencies.wispMoshi)
  implementation(project(":misk"))
  implementation(project(":misk-service"))
  runtimeOnly(Dependencies.hsqldb)
  runtimeOnly(Dependencies.mysql)
  runtimeOnly(Dependencies.openTracingJdbc)
  runtimeOnly(Dependencies.postgresql)

  testImplementation(Dependencies.assertj)
  testImplementation(Dependencies.junitApi)
  testImplementation(Dependencies.kotlinTest)
  testImplementation(Dependencies.mockitoCore)
  testImplementation(Dependencies.openTracingDatadog)
  testImplementation(Dependencies.openTracingMock)
  testImplementation(Dependencies.wispContainersTesting)
  testImplementation(project(":misk-jdbc-testing"))
  testImplementation(project(":misk-testing"))
}
