#!/bin/sh

usage() {
  cat << EOF
  Usage :: misk-web <opts>

  Runs command on all @misk/ packages and tabs

  -h    Usage

  -a    'build' all, clean install and build tab

  -b    'build' *if directory hash is different* clean install and build tab

  -c    'clean' all build folders and caches

  -d    'start' webpack-dev-server on first found tab
        note: only run when docker container is mounted with a single tab

  -g    'ci-build', same as '-b' but without linting for faster CI builds

  -l    'lint' run Prettier linting

  -o    compute a md5 hash over the current directory and stores in .hash file

  -m    compute a md5 hash over the current directory and stores in .hash file, creates .hashdiff file if there is an existing hash
        exclude patterns: cachedUrls, lib, node_modules, .hash

  -r    'refresh' local web/node_modules from Docker image /node_modules

  -w    overide location for web mount point
        default: '/web'

  -x    run next option on all tabs *if directory hash is different*

  -z    run <optarg> command


  Must run script in the following directory structure
  For Docker container, mount localpath:...web/ -> /web/

  /web
    misk-build.sh
    node_modules/
    tabs/
      tab1/
        package.json
      tab2/
        package.json
      tab3/
        package.json
      ...
EOF
    exit 0
}

LABEL=""
CMD=""
WEB="/web"
HD="false"

hashDir() {
    tar --exclude="cachedUrls" --exclude="lib" --exclude="node_modules" --exclude=".DS_Store" --exclude=".hash" --exclude="yarn.lock" -cf - . | md5sum 2>&1
}

hashDiff() {
    newHash=$(hashDir | sed 's/[[:space:]]//g')
    if [ -f .hash ]; then
        oldHash=$(sed 's/[[:space:]]//g' < .hash)
        if [ "$oldHash" = "$newHash" ]; then
            echo "${oldHash} ${newHash} false"
        else
            echo "${oldHash} ${newHash} true"
        fi

    else
        echo "${newHash} true"
    fi
}

stashNodeModules() {
    echo "[STASH] Removing tab node_modules and linking to node_modules from Docker image"
    # Remove any previous node_modules links or directories
    rm -f ./node_modules
    rm -rf ./node_modules
    # Link to cached node_modules in Docker image
    ln -s /node_modules .
}

refreshNodeModules() {
    # Install local web/node_modules if not already present, not in CI environments
    [ ! -d ${WEB}/node_modules ] && ! printenv | grep -q "CI" && echo "[REFRESH] Updating local web/node_modules/ from Docker image" && cp -r /node_modules ${WEB}/node_modules
}

restoreNodeModules() {
    echo "[RESTORE] Restoring symlink of node_modules to local web/node_modules directory"
    # Relink back to web/node_modules
    ln -s ${WEB}/node_modules .
}

runCmd() {
    echo "[RUNCMD]: ${WEB}/*/* $LABEL HD: '$HD' CMD: '$CMD'"

    refreshNodeModules

    for dir in ${WEB}/*/* ; do
        dir=${dir%*/}
        if [ -d $dir ] && [ "$dir" = "${dir%"node_modules"*}" ]; then
            cd $dir || continue
            if [ "$HD" = "true" ]; then
                diffResult=$(hashDiff)
                echo "[HASH DIFF] $dir $diffResult"
                stashNodeModules
                # Run command if hashdiff is different
                echo "$LABEL $dir" && echo "$diffResult" | grep -Fq "true" && $CMD
                # Run command anyways if there is no lib directory
                [ ! -d $dir/lib ] && echo "$LABEL $dir" && $CMD
            else
                stashNodeModules
                # Run command if no hashdiff check required
                echo "$LABEL $dir" && $CMD
            fi
            restoreNodeModules
            # Update hash after every command
            hashDir | tee .hash
            echo "[DONE]" && echo ""
        fi
    done
}

reset() {
    LABEL=""
    CMD=""
    HD="false"
}

while getopts "h?abcdglomrwxz:" opt; do
    case "$opt" in
        h|\?)   usage && exit 0   ;;
        a)      LABEL="[BUILD ALL]" && CMD='yarn build' && runCmd && reset   ;;
        b)      LABEL="[BUILD]" && HD="true" && CMD='yarn build' && runCmd && reset   ;;
        c)      LABEL="[CLEAN]" && CMD='yarn clean' && runCmd && reset    ;;
        d)      LABEL="[DEV]" && CMD='yarn start' && runCmd && reset   ;;
        g)      LABEL="[CI-BUILD]" && HD="true" && CMD='yarn ci-build' && runCmd && reset   ;;
        l)      LABEL="[LINT]" && CMD='yarn run lint' && runCmd && reset  ;;
        o)      LABEL="[MD5 HASH]" && CMD='hashDir | tee .hash' && runCmd && reset   ;;
        m)      LABEL="[MD5 HASHDIFF]" && CMD='hashDiff' && runCmd && reset   ;;
        r)      restoreNodeModules && reset    ;;
        w)      LABEL="[ALT WEB LOCATION]" && WEB="${OPTARG}" && reset    ;;
        x)      LABEL="[HD=\"true\"]" && HD="true"    ;;
        z)      LABEL="[CMD]" && CMD="${OPTARG}" && runCmd && reset   ;;
    esac
done

exit 0