package misk.dynamodb

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import java.util.Date

@DynamoDBTable(tableName = "")
abstract class DyTimestampedEntity : DyEntity() {

  @DynamoDBAttribute(attributeName = "created_at")
  @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
  var created_at: Date = Date()

  @DynamoDBAttribute(attributeName = "updated_at")
  @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
  var updated_at: Date = Date()
}
