package misk.dynamodb

import java.util.Date

/**
 * Interface for a timestamped entity.
 */
interface DyTimestampedEntity {

  /**
   * @DynamoDBAttribute(attributeName = "created_at")
   * @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
   */
  var created_at: Date

  /**
   * @DynamoDBAttribute(attributeName = "updated_at")
   * @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
   */
  var updated_at: Date
}
