CREATE TABLE movie(
    id BIGINT NOT NULL AUTO_INCREMENT primary key,
    name VARCHAR(191) NOT NULL,
    genre VARCHAR(191) NOT NULL,
    version INT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT NOW(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT NOW(3) ON UPDATE NOW(3)
)