name: Build docs site (& deploy if on master to gh-pages)

on:
  pull_request:
  push:
    branches:
      - master

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Generate API docs
        run: gradle dokkaGfm

      - name: Prep mkdocs
        run: .github/workflows/prepare_mkdocs.sh

      - name: Build mkdocs
        run: |
          pip3 install mkdocs mkdocs-material mkdocs-macros-plugin
          mkdocs build

      - name: Deploy 🚀
        if: success() && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_CLIPPY_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: site # The folder the action should deploy.
          SINGLE_COMMIT: true
